### ISSUE TITLE
[vali] driver config files

### ISSUE THREAD

**Issue by Meulengracht** [Meulengracht/MollenOS#281]
Refactor the current .mdrv files and switch to a yaml format, relies on the feature #280.

Then we want a format where we can both specify address spaces if neccessary for hardwired drivers (etc CMOS on x86), and we want to be able to support multiple vendor/product numbers

```
driver:
  vendors:
  - vendorid:
      - productid0
      - productid1
  
  type:
  - class: 0
  - subclass: 0

  resources:
  - type: io
    base: 0x70
    length: 0x71
  - type: mmio
    base: 0xE0000000
    length: 0x1000 
```
